#+title: Progenitor stars calculated with small reaction networks should not be used as initial conditions for core collapse
#+BEGIN_html
<p align="center">
<a href="https://github.com/mathren/small_net_progenitors/blob/master/manuscript/CHE_networks.pdf">
<img src="https://img.shields.io/badge/article-pdf-blue.svg?style=flat" alt="Read the article"/>
</a>
<a href="https://doi.org/10.5281/zenodo.11375523"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.11375523.svg" alt="DOI"></a>
</p>
#+END_html

** Main take home point

If you need progenitors to study multi-dimensional neutrino
magneto-hydrodynamics of stellar explosions, whether including
rotation or not, do not waste your precious CPUh/GPUh on progenitors
computed with =approx= nuclear reaction networks.

These are great for many things, but not to calculate the weak
reactions that determine the fraction of free electrons in the core.
They introduce a *known* systematic uncertainty comparable to unknown in
many other physical ingredients, and thus muddy the waters and prevent
learning robust conclusion from the explosion of progenitors computed
with these.

** How to reproduce

From [[https://doi.org/10.5281/zenodo.11375523][zenodo]] download the MESA results, stored in
=40_rot0.6_large_net.xz= for the 128-isotope model run with =mesa_128.net=
and =40_rot0.6_small_net.tar.xz= for the 22-isotope
(=approx21_plus_cr56.net=) model. These were computed with [[https://docs.mesastar.org/en/latest/][MESA]] version
r24.03.1.

Download also =scripts.tar.xz= from
zenodo and unpack all in the same folder (or use the =scripts/= folder
here).

Run =compare_two_models.py= to produce the figure in the research note.
It depends on functions defined in the other =*.py= files in =scripts/=.
